version: "3.3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=8888
    # env_file:
    #   ./.env